stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - dataset
  preprocess:
    cmd: python src/text_preprocessing.py
    deps:
    - dataset
    - src/text_preprocessing.py
    outs:
    - output/preprocessed_data.joblib
    - output/preprocessor.joblib
